In [1]:
# !pip install numpy

In [2]:
import numpy as np


In [3]:
import numpy as np

In [4]:
ar1=np.array([1,2,4,6,8,9])
type(ar1)

numpy.ndarray

In [5]:
ar2=np.array([2,4,6,7,8,9])

In [6]:
ar1+ar2

array([ 3,  6, 10, 13, 16, 18])

In [7]:
aree=np.array([1,2,3,4,5])
arre2=np.array([5,6,7,8,9,])

In [8]:
num=[1,2,3,5,6]
num1=[2,3,4,6,6]

In [9]:
num+num1

[1, 2, 3, 5, 6, 2, 3, 4, 6, 6]

In [10]:
aree+arre2

array([ 6,  8, 10, 12, 14])

In [11]:
# array using indexing 
numbers=np.array([1,2,3,4,5,6,7,8,9])

In [12]:
num=numbers

In [13]:
numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
num[0]

np.int64(1)

In [15]:
# adding new elements to array
num=np.append(num,10)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
num=np.insert(num,0,0)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
num[0:5]
num[5]

np.int64(5)

In [18]:
num=np.delete(num,0)
num
num=np.insert(num,2,10)

In [19]:
num[0:10:2]  #slicing with step

array([ 1, 10,  4,  6,  8])

In [20]:
num.shape

(11,)

In [21]:
x=np.array([1,2,3,4,5,6,7,8,9])
x=x.reshape(3,3)  #reshaping array into 3*3 matrix

In [22]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# all opration on numpy array 
x.sum()
x.mean()
x.max()
x.min()

np.int64(1)

In [24]:
z = np.zeros((2,3))
print("Zeros:\n", z)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
name=np.array(['pavan','kumar','reddy'])    
name    
name.dtype

dtype('<U5')

In [26]:
numbers=np.array([2,5,9,6,7,2,6,3,8,9,4,5])
numbers.sort()

In [27]:
numbers

array([2, 2, 3, 4, 5, 5, 6, 6, 7, 8, 9, 9])

In [28]:
num.sum()

np.int64(65)

In [29]:
num.min()

np.int64(1)

In [30]:

# pandas
import pandas as pd

In [31]:
data={
    "name":["pavan", "rahul","sai","nilesh"],
    "age":[19,20,25,24],
    "grade":["A","B","C","D"],
    "qulification":["Bca","Mca","Bsc","Bcom"],
    "village":["kosam" ,"narsapur","anantapur","hyderabad"],
    "state":["telangana","andhra pradesh","karnataka","maharashtra"]
}

In [32]:
data=pd.DataFrame(data)

In [33]:
data

name  age grade qulification    village           state
0   pavan   19     A          Bca      kosam       telangana
1   rahul   20     B          Mca   narsapur  andhra pradesh
2     sai   25     C          Bsc  anantapur       karnataka
3  nilesh   24     D         Bcom  hyderabad     maharashtra

In [34]:
data=data.head()

In [35]:
data.tail()

name  age grade qulification    village           state
0   pavan   19     A          Bca      kosam       telangana
1   rahul   20     B          Mca   narsapur  andhra pradesh
2     sai   25     C          Bsc  anantapur       karnataka
3  nilesh   24     D         Bcom  hyderabad     maharashtra

In [36]:
data.describe()

age
count   4.00000
mean   22.00000
std     2.94392
min    19.00000
25%    19.75000
50%    22.00000
75%    24.25000
max    25.00000

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   name          4 non-null      object
 1   age           4 non-null      int64 
 2   grade         4 non-null      object
 3   qulification  4 non-null      object
 4   village       4 non-null      object
 5   state         4 non-null      object
dtypes: int64(1), object(5)
memory usage: 324.0+ bytes


In [38]:
data.shape

(4, 6)

In [39]:
data.columns
data.dtypes
data['name']

0     pavan
1     rahul
2       sai
3    nilesh
Name: name, dtype: object

In [40]:
# import data in csv 

In [41]:
# ! pip install pandas

In [42]:
import pandas as pd

In [43]:

bmw = pd.read_csv("csv data files/BMW.csv")


In [44]:
bmw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Model                 50000 non-null  object 
 1   Year                  50000 non-null  int64  
 2   Region                50000 non-null  object 
 3   Color                 50000 non-null  object 
 4   Fuel_Type             50000 non-null  object 
 5   Transmission          50000 non-null  object 
 6   Engine_Size_L         50000 non-null  float64
 7   Mileage_KM            50000 non-null  int64  
 8   Price_USD             50000 non-null  int64  
 9   Sales_Volume          50000 non-null  int64  
 10  Sales_Classification  50000 non-null  object 
dtypes: float64(1), int64(4), object(6)
memory usage: 4.2+ MB


In [45]:
bmw.sample(10)

Model  Year         Region   Color Fuel_Type Transmission  \
38721        i3  2020           Asia   White    Diesel       Manual   
8830         i8  2011  North America    Blue  Electric    Automatic   
16921        i8  2013         Europe    Blue  Electric    Automatic   
38985  5 Series  2015         Africa   White    Petrol    Automatic   
26006        X6  2024  North America    Blue  Electric       Manual   
24508  7 Series  2010  North America    Blue    Hybrid    Automatic   
170    7 Series  2012  North America  Silver    Hybrid    Automatic   
43867  5 Series  2024           Asia    Grey    Diesel       Manual   
29871        X5  2014  South America   White    Diesel    Automatic   
13409        X6  2010         Africa    Blue    Diesel    Automatic   

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
38721            3.6       74524      56813          6381                  Low  
8830             2.9      115567      95341          4167                  Low  
16921            2.1       91700      55155          9789                 High  
38985            2.6       88158      50958          2108                  Low  
26006            4.6       68371      49621          2489                  Low  
24508            1.7      154317     100845          3341                  Low  
170              4.2      178603      42764          9856                 High  
43867            3.4      128890      86701          7115                 High  
29871            2.5        1424     103016          7823                 High  
13409            3.2       92895      36692          9481                 High

In [46]:
updateddata=bmw.drop(["Region" ,"Model"] ,axis=1)

In [47]:
updateddata

Year   Color Fuel_Type Transmission  Engine_Size_L  Mileage_KM  \
0      2016     Red    Petrol       Manual            3.5      151748   
1      2013     Red    Hybrid    Automatic            1.6      121671   
2      2022    Blue    Petrol    Automatic            4.5       10991   
3      2024    Blue    Petrol    Automatic            1.7       27255   
4      2020   Black    Diesel       Manual            2.1      122131   
...     ...     ...       ...          ...            ...         ...   
49995  2014     Red    Hybrid       Manual            4.6      151030   
49996  2023  Silver  Electric       Manual            4.2      147396   
49997  2010     Red    Petrol    Automatic            4.5      174939   
49998  2020   White  Electric    Automatic            3.8        3379   
49999  2020    Blue    Diesel       Manual            3.3      171003   

       Price_USD  Sales_Volume Sales_Classification  
0          98740          8300                 High  
1          79219          3428                  Low  
2         113265          6994                  Low  
3          60971          4047                  Low  
4          49898          3080                  Low  
...          ...           ...                  ...  
49995      42932          8182                 High  
49996      48714          9816                 High  
49997      46126          8280                 High  
49998      58566          9486                 High  
49999      77492          1764                  Low  

[50000 rows x 9 columns]

In [48]:
bmw[ (bmw["Sales_Volume"]== 8261)  & (bmw["Model"]=="X3") ]

Model  Year  Region  Color Fuel_Type Transmission  Engine_Size_L  \
44311    X3  2018  Europe  Black  Electric       Manual            3.6   

       Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
44311      120797      81629          8261                 High

In [49]:
bmw.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Model                 50000 non-null  object 
 1   Year                  50000 non-null  int64  
 2   Region                50000 non-null  object 
 3   Color                 50000 non-null  object 
 4   Fuel_Type             50000 non-null  object 
 5   Transmission          50000 non-null  object 
 6   Engine_Size_L         50000 non-null  float64
 7   Mileage_KM            50000 non-null  int64  
 8   Price_USD             50000 non-null  int64  
 9   Sales_Volume          50000 non-null  int64  
 10  Sales_Classification  50000 non-null  object 
dtypes: float64(1), int64(4), object(6)
memory usage: 4.2+ MB


In [50]:
bmw.head(100)

Model  Year         Region   Color Fuel_Type Transmission  \
0   5 Series  2016           Asia     Red    Petrol       Manual   
1         i8  2013  North America     Red    Hybrid    Automatic   
2   5 Series  2022  North America    Blue    Petrol    Automatic   
3         X3  2024    Middle East    Blue    Petrol    Automatic   
4   7 Series  2020  South America   Black    Diesel       Manual   
..       ...   ...            ...     ...       ...          ...   
95        X6  2022           Asia   White  Electric       Manual   
96        X5  2024           Asia    Blue    Hybrid    Automatic   
97        i8  2011         Europe     Red    Hybrid    Automatic   
98        X5  2019         Africa    Blue  Electric       Manual   
99        X1  2021           Asia  Silver    Diesel       Manual   

    Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
0             3.5      151748      98740          8300                 High  
1             1.6      121671      79219          3428                  Low  
2             4.5       10991     113265          6994                  Low  
3             1.7       27255      60971          4047                  Low  
4             2.1      122131      49898          3080                  Low  
..            ...         ...        ...           ...                  ...  
95            1.9      182027      35951          3389                  Low  
96            2.6      120597      95900          8581                 High  
97            3.8      184765      44846          1431                  Low  
98            2.1      161177      95908          2775                  Low  
99            2.6       84621     119897          4601                  Low  

[100 rows x 11 columns]

In [51]:
bmw.iloc[0]

Model                   5 Series
Year                        2016
Region                      Asia
Color                        Red
Fuel_Type                 Petrol
Transmission              Manual
Engine_Size_L                3.5
Mileage_KM                151748
Price_USD                  98740
Sales_Volume                8300
Sales_Classification        High
Name: 0, dtype: object

In [52]:
bmw.loc[:,["Model","Color"]]

Model   Color
0      5 Series     Red
1            i8     Red
2      5 Series    Blue
3            X3    Blue
4      7 Series   Black
...         ...     ...
49995        i3     Red
49996        i3  Silver
49997  5 Series     Red
49998        i3   White
49999        X1    Blue

[50000 rows x 2 columns]

In [53]:
bmw.loc[ ["Color","Year"]]

KeyError: "None of [Index(['Color', 'Year'], dtype='object')] are in the [index]"

In [ ]:
# 10/10/25

In [ ]:
# data filtering

In [ ]:
bmw[bmw["Color"]=="Black" > 2013]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

[0        False
 1        False
 2        False
 3        False
 4         True
          ...  
 49995    False
 49996    False
 49997    False
 49998    False
 49999    False
 Name: Color, Length: 50000, dtype: bool]

In [ ]:
bmw["Model"].unique()

array(['5 Series', 'i8', 'X3', '7 Series', 'M5', '3 Series', 'X1', 'M3',
       'X5', 'i3', 'X6'], dtype=object)

In [ ]:
bmw[bmw["Year"]>2013]



Model  Year         Region   Color Fuel_Type Transmission  \
0      5 Series  2016           Asia     Red    Petrol       Manual   
2      5 Series  2022  North America    Blue    Petrol    Automatic   
3            X3  2024    Middle East    Blue    Petrol    Automatic   
4      7 Series  2020  South America   Black    Diesel       Manual   
5      5 Series  2017    Middle East  Silver    Diesel       Manual   
...         ...   ...            ...     ...       ...          ...   
49992        i3  2017    Middle East    Blue    Petrol    Automatic   
49995        i3  2014           Asia     Red    Hybrid       Manual   
49996        i3  2023    Middle East  Silver  Electric       Manual   
49998        i3  2020           Asia   White  Electric    Automatic   
49999        X1  2020  North America    Blue    Diesel       Manual   

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
0                3.5      151748      98740          8300                 High  
2                4.5       10991     113265          6994                  Low  
3                1.7       27255      60971          4047                  Low  
4                2.1      122131      49898          3080                  Low  
5                1.9      171362      42926          1232                  Low  
...              ...         ...        ...           ...                  ...  
49992            3.9       79874     115046          9015                 High  
49995            4.6      151030      42932          8182                 High  
49996            4.2      147396      48714          9816                 High  
49998            3.8        3379      58566          9486                 High  
49999            3.3      171003      77492          1764                  Low  

[36734 rows x 11 columns]

In [ ]:
bmw["Color"]

0           Red
1           Red
2          Blue
3          Blue
4         Black
          ...  
49995       Red
49996    Silver
49997       Red
49998     White
49999      Blue
Name: Color, Length: 50000, dtype: object

In [ ]:
x3_model=bmw[(bmw["Color"] == "Blue") & (bmw["Fuel_Type"] == "Petrol") & (bmw["Year"] ==2023) & (bmw["Price_USD"] < 85255) & (bmw["Model"]=="X3")]

In [ ]:
x3_model

Model  Year         Region Color Fuel_Type Transmission  Engine_Size_L  \
9147     X3  2023  South America  Blue    Petrol    Automatic            1.9   
14945    X3  2023         Europe  Blue    Petrol    Automatic            2.0   
27327    X3  2023         Europe  Blue    Petrol    Automatic            1.9   
33803    X3  2023         Africa  Blue    Petrol    Automatic            3.1   
39041    X3  2023         Africa  Blue    Petrol       Manual            1.8   

       Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
9147       132565      58682          8310                 High  
14945      137028      61964          1973                  Low  
27327      192583      48873          8468                 High  
33803      104198      46400          6290                  Low  
39041      138326      67606           399                  Low

In [ ]:
x3_model[ (x3_model["Sales_Classification"]=="Low") & (x3_model["Price_USD"]<80000) ]

Model  Year  Region Color Fuel_Type Transmission  Engine_Size_L  \
14945    X3  2023  Europe  Blue    Petrol    Automatic            2.0   
33803    X3  2023  Africa  Blue    Petrol    Automatic            3.1   
39041    X3  2023  Africa  Blue    Petrol       Manual            1.8   

       Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
14945      137028      61964          1973                  Low  
33803      104198      46400          6290                  Low  
39041      138326      67606           399                  Low

In [ ]:
bmw["Region"].unique()

(6,)

In [ ]:
# 

In [ ]:
bmw

Model  Year         Region   Color Fuel_Type Transmission  \
0      5 Series  2016           Asia     Red    Petrol       Manual   
1            i8  2013  North America     Red    Hybrid    Automatic   
2      5 Series  2022  North America    Blue    Petrol    Automatic   
3            X3  2024    Middle East    Blue    Petrol    Automatic   
4      7 Series  2020  South America   Black    Diesel       Manual   
...         ...   ...            ...     ...       ...          ...   
49995        i3  2014           Asia     Red    Hybrid       Manual   
49996        i3  2023    Middle East  Silver  Electric       Manual   
49997  5 Series  2010    Middle East     Red    Petrol    Automatic   
49998        i3  2020           Asia   White  Electric    Automatic   
49999        X1  2020  North America    Blue    Diesel       Manual   

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
0                3.5      151748      98740          8300                 High  
1                1.6      121671      79219          3428                  Low  
2                4.5       10991     113265          6994                  Low  
3                1.7       27255      60971          4047                  Low  
4                2.1      122131      49898          3080                  Low  
...              ...         ...        ...           ...                  ...  
49995            4.6      151030      42932          8182                 High  
49996            4.2      147396      48714          9816                 High  
49997            4.5      174939      46126          8280                 High  
49998            3.8        3379      58566          9486                 High  
49999            3.3      171003      77492          1764                  Low  

[50000 rows x 11 columns]

In [ ]:
bmw=[bmw(["Mileage_KM"].between(121671,151748)) & (bmw["Color"]=="Red") ]

AttributeError: 'list' object has no attribute 'between'

In [54]:
data

name  age grade qulification    village           state
0   pavan   19     A          Bca      kosam       telangana
1   rahul   20     B          Mca   narsapur  andhra pradesh
2     sai   25     C          Bsc  anantapur       karnataka
3  nilesh   24     D         Bcom  hyderabad     maharashtra

In [55]:
bmw

Model  Year         Region   Color Fuel_Type Transmission  \
0      5 Series  2016           Asia     Red    Petrol       Manual   
1            i8  2013  North America     Red    Hybrid    Automatic   
2      5 Series  2022  North America    Blue    Petrol    Automatic   
3            X3  2024    Middle East    Blue    Petrol    Automatic   
4      7 Series  2020  South America   Black    Diesel       Manual   
...         ...   ...            ...     ...       ...          ...   
49995        i3  2014           Asia     Red    Hybrid       Manual   
49996        i3  2023    Middle East  Silver  Electric       Manual   
49997  5 Series  2010    Middle East     Red    Petrol    Automatic   
49998        i3  2020           Asia   White  Electric    Automatic   
49999        X1  2020  North America    Blue    Diesel       Manual   

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
0                3.5      151748      98740          8300                 High  
1                1.6      121671      79219          3428                  Low  
2                4.5       10991     113265          6994                  Low  
3                1.7       27255      60971          4047                  Low  
4                2.1      122131      49898          3080                  Low  
...              ...         ...        ...           ...                  ...  
49995            4.6      151030      42932          8182                 High  
49996            4.2      147396      48714          9816                 High  
49997            4.5      174939      46126          8280                 High  
49998            3.8        3379      58566          9486                 High  
49999            3.3      171003      77492          1764                  Low  

[50000 rows x 11 columns]

In [56]:
bmw.shape

(50000, 11)

In [57]:
bmw.sample(10)

Model  Year         Region   Color Fuel_Type Transmission  \
3223     X3  2023         Africa    Blue    Diesel    Automatic   
8276     X1  2020         Europe   Black  Electric       Manual   
4639     M3  2011  South America    Blue    Hybrid       Manual   
2841     i8  2011         Europe  Silver    Hybrid    Automatic   
43202    X5  2014  South America     Red    Petrol       Manual   
41094    M3  2015         Africa    Grey  Electric       Manual   
4972     X6  2014         Africa     Red    Hybrid    Automatic   
42372    M5  2022         Africa   Black    Petrol    Automatic   
15342    X1  2010         Africa    Grey  Electric    Automatic   
48653    M5  2015  North America    Blue    Hybrid    Automatic   

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
3223             3.5       98020      39003           222                  Low  
8276             4.0      157767     117810          2395                  Low  
4639             1.9      180797      92237          7722                 High  
2841             2.7      196277     111086          2425                  Low  
43202            2.2      178862      75045          8059                 High  
41094            4.3      188021     119015          6609                  Low  
4972             2.1       65202      59338          2617                  Low  
42372            3.3      182519      33757          4727                  Low  
15342            2.9      176698      98977          4117                  Low  
48653            3.9       14852      78109          4447                  Low

In [72]:
most_sales=bmw[(bmw["Year"]==2023) & (bmw["Sales_Classification"]=="High") & (bmw["Transmission"]=="Manual") & (bmw["Color"]== "Black") ]

In [75]:
most_sales.sort_values(["Engine_Size_L","Sales_Volume"],ascending=False)

Model  Year         Region  Color Fuel_Type Transmission  \
28405  7 Series  2023         Africa  Black  Electric       Manual   
36263        M3  2023  South America  Black    Hybrid       Manual   
13419        X5  2023  North America  Black    Hybrid       Manual   
16985        i3  2023         Europe  Black    Petrol       Manual   
6620         X3  2023         Europe  Black  Electric       Manual   
...         ...   ...            ...    ...       ...          ...   
28460        M5  2023         Europe  Black    Diesel       Manual   
22720        M5  2023           Asia  Black    Petrol       Manual   
1419         M3  2023           Asia  Black  Electric       Manual   
11367        X6  2023  South America  Black  Electric       Manual   
2195   7 Series  2023  North America  Black    Petrol       Manual   

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
28405            5.0       86600      48093          8196                 High  
36263            4.9      180543      48286          9528                 High  
13419            4.9      120494      57674          8963                 High  
16985            4.9       54055      40721          8360                 High  
6620             4.9      143830      96215          8052                 High  
...              ...         ...        ...           ...                  ...  
28460            1.7       91622      91798          9233                 High  
22720            1.7       12338      79245          8892                 High  
1419             1.6       53042      59651          9583                 High  
11367            1.6       55017      69155          9416                 High  
2195             1.5       67239      95084          8077                 High  

[85 rows x 11 columns]

In [ ]:
bmw["Mileage_KM"].unique()

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [67]:
bmw[bmw["Mileage_KM"]== 199996]

Model  Year  Region   Color Fuel_Type Transmission  Engine_Size_L  \
1009    X3  2011  Europe  Silver    Hybrid    Automatic            3.8   

      Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
1009      199996      50904          3775                  Low

In [ ]:
bmw.rename( columns={"Year":"sal",})

Model   sal         Region   Color Fuel_Type Transmission  \
0      5 Series  2016           Asia     Red    Petrol       Manual   
1            i8  2013  North America     Red    Hybrid    Automatic   
2      5 Series  2022  North America    Blue    Petrol    Automatic   
3            X3  2024    Middle East    Blue    Petrol    Automatic   
4      7 Series  2020  South America   Black    Diesel       Manual   
...         ...   ...            ...     ...       ...          ...   
49995        i3  2014           Asia     Red    Hybrid       Manual   
49996        i3  2023    Middle East  Silver  Electric       Manual   
49997  5 Series  2010    Middle East     Red    Petrol    Automatic   
49998        i3  2020           Asia   White  Electric    Automatic   
49999        X1  2020  North America    Blue    Diesel       Manual   

       Engine_Size_L  Mileage_KM  Price_USD  Sales_Volume Sales_Classification  
0                3.5      151748      98740          8300                 High  
1                1.6      121671      79219          3428                  Low  
2                4.5       10991     113265          6994                  Low  
3                1.7       27255      60971          4047                  Low  
4                2.1      122131      49898          3080                  Low  
...              ...         ...        ...           ...                  ...  
49995            4.6      151030      42932          8182                 High  
49996            4.2      147396      48714          9816                 High  
49997            4.5      174939      46126          8280                 High  
49998            3.8        3379      58566          9486                 High  
49999            3.3      171003      77492          1764                  Low  

[50000 rows x 11 columns]